version: '3.7'

services: 
  jenkins-service:
    image: mysql
    ports:
      - 9003:3306
      - 33060:33060
    container_name: mysql
    hostname: mysql
    volumes:
      - C:/Users/stefa/Documents/Docker/MySQL:/var/lib/mysql
    environment:
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - GOSU_VERSION=1.7
      - MYSQL_MAJOR=8.0
      - MYSQL_VERSION=8.0.16-2debian9
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root

networks:
  default:
    external:
      name: smartheating